kind: pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: compile
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet restore DiskSearch
    - dotnet publish --no-restore DiskSearch

- name: Test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet restore Tests
    - mkdir -p Tests/bin/Debug/net5.0
    - cp -r TestData Tests/bin/Debug/net5.0/
    - mkdir -p Tests/bin/Debug/net5.0/index
    - dotnet test --no-restore Tests
  depends_on:
    - compile
