 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
     steps:
       - checkout
       - run: dotnet build
   test:
     executor: win/default
     steps:
       - checkout
       - run: dotnet test
       
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test
